fn main() {
    let caps_dir = std::path::PathBuf::from("capabilities");
    let updater_cap = caps_dir.join("updater.json");

    // Check crate feature via env var (not #[cfg] which checks build script's own features)
    if std::env::var("CARGO_FEATURE_SELF_UPDATE").is_ok() {
        let content = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "updater",
  "description": "Updater permissions (auto-generated by build.rs when self-update feature is enabled)",
  "windows": ["main"],
  "permissions": [
    "updater:default",
    "process:allow-restart"
  ]
}
"#;
        // Only write if content changed to avoid triggering Tauri's file watcher loop
        let needs_write = match std::fs::read_to_string(&updater_cap) {
            Ok(existing) => existing != content,
            Err(_) => true,
        };
        if needs_write {
            std::fs::write(&updater_cap, content).expect("Failed to write updater capability");
        }
    } else {
        if updater_cap.exists() {
            let _ = std::fs::remove_file(&updater_cap);
        }
    }

    tauri_build::build()
}
