fn main() {
    let caps_dir = std::path::PathBuf::from("capabilities");
    let updater_cap = caps_dir.join("updater.json");

    // Check crate feature via env var (not #[cfg] which checks build script's own features)
    if std::env::var("CARGO_FEATURE_SELF_UPDATE").is_ok() {
        let content = r#"{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "updater",
  "description": "Updater permissions (auto-generated by build.rs when self-update feature is enabled)",
  "windows": ["main"],
  "permissions": [
    "updater:default",
    "process:allow-restart"
  ]
}
"#;
        std::fs::write(&updater_cap, content).expect("Failed to write updater capability");
    } else {
        let _ = std::fs::remove_file(&updater_cap);
    }

    tauri_build::build()
}
